package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("env.CONTAINER_APP_JOB_NAME", "neolore-queue-pipeline-job")
        }
        add {
            param("env.ACR_NAME", "neolorequeueacrgnqgt5titvw3a")
        }
        add {
            param("env.AZURE_TENANT_ID", "82fcdccc-2d47-47c7-8cfd-c9f0af78aee3")
        }
        add {
            param("env.AZURE_RESOURCE_GROUP", "rg-neolore-queue-analytics")
        }
        add {
            param("env.AZURE_SUBSCRIPTION_ID", "18881902-3917-4da0-b708-bf35a34ecf53")
        }
    }
}
